site_name: Unicode

theme:
  name: 'material'
  palette:
    primary: 'Grey'
    accent: 'Green'
  favicon: 'images/favicon.png'
  language: 'ru'
  feature:
    tabs: true
#  logo: 'images/favicon.png'
#  support: 'images/support.png'

extra_css:
  - 'css/my-material-tweaks.css'

plugins:
  - macros

extra:
  c:
    Green: style="color:#008000;background-color:#FFFFFF"
    Red: style="color:#FF0000;background-color:#FFFFFF"

#pages: Depricated!

nav:

    - Основы Юникода: 'index.md'

markdown_extensions:
  - admonition
  - attr_list
  - meta
#  - codehilite:
#      guess_lang: true
#  - pymdownx.highlight:
#      linenums: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys:
       camel_case: true
       strict: false
  - toc:
      permalink: true
#  - mdx_inline_graphviz 
